# Lint every Dockerfile. Add to .gitlab-ci.yml. Needs pipelines/docker/lint/Taskfile.yml
# copied to .taskfiles/docker/lint/Taskfile.yml and included as `docker:lint`.

docker-lint:
  image: ghcr.io/twanvanparidon/ci-runner/docker:1.2.0@sha256:e597a03c863305ac33a93d9562b1472046df40633cd051cc463c70846cf90491
  script: [task docker:lint]
